### ISSUE TITLE
Missing errors in Appsignal

### ISSUE THREAD

**Issue by leander-karp** [ivx/ears#8]
We were missing errors in Appsignal even though we added Ears Appsignal middleware. We solved the issue by adding `appsignal_instrument_method` into our consumer as well. We should think about extending the middleware with instrumentation.

**Comment by brerx** [comment]
@leander-karp in which app did you solve it like that?

**Comment by tristandruyen** [comment]
We did not solve it, we mistakenly thought it did...

**Comment by spaceneedle2019** [comment]
You can handle that problem by setting up a sleep for the AppSignal agent like [this](https://github.com/ivx/notifications/pull/47/commits/669c5b757bc6595b28ab9329327d63e43bd772ab):

```ruby
begin
   Ears.run!
 ensure
   Appsignal.stop
   sleep 5
 end
```
